# Generated by Django 3.0.2 on 2020-01-13 09:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eLearningApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 9, 7, 48, 937267, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 9, 7, 48, 939875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 9, 7, 48, 939898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 9, 7, 48, 939875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 9, 7, 48, 939898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='relatedcourse',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 9, 7, 48, 937989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='text',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 9, 7, 48, 939875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='text',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 9, 7, 48, 939898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 9, 7, 48, 939875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 9, 7, 48, 939898, tzinfo=utc)),
        ),
    ]
