# Generated by Django 3.0.1 on 2020-01-03 21:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eLearningApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 21, 46, 34, 977148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 21, 46, 34, 979669, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 21, 46, 34, 979693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 21, 46, 34, 979669, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 21, 46, 34, 979693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='relatedcourse',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 21, 46, 34, 977786, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='text',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 21, 46, 34, 979669, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='text',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 21, 46, 34, 979693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 21, 46, 34, 979669, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 21, 46, 34, 979693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_related', to='eLearningApp.User'),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_related', to='eLearningApp.User'),
        ),
        migrations.AlterField(
            model_name='text',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_related', to='eLearningApp.User'),
        ),
        migrations.AlterField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_related', to='eLearningApp.User'),
        ),
    ]
