# Generated by Django 3.0.2 on 2020-01-23 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eLearningApp', '0004_auto_20200115_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 6, 33, 0, 100218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 6, 33, 0, 100257, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 6, 33, 0, 104490, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 6, 33, 0, 104528, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 6, 33, 0, 104490, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 6, 33, 0, 104528, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='relatedcourse',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 6, 33, 0, 101809, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='text',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 6, 33, 0, 104490, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='text',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 6, 33, 0, 104528, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 6, 33, 0, 104490, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 6, 33, 0, 104528, tzinfo=utc)),
        ),
    ]
